# -*- coding: utf-8 -*-
"""EM_and_K-means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkDyhYjn3epjkuwMX0CgJ3FCcZRuSyRI
"""

#COMPARISON BETWEEN ACCURACIES OF EM AND K-MEANS ALGORITHM ON IRIS DATASET

from sklearn import datasets
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target)
model =KMeans(n_clusters=3)
model.fit(X_train,y_train)
metrics.accuracy_score(y_test,model.predict(X_test))

from sklearn.mixture import GaussianMixture
model2 = GaussianMixture(n_components=3)
model2.fit(X_train,y_train)
model2.score
metrics.accuracy_score(y_test,model2.predict(X_test))

