# -*- coding: utf-8 -*-
"""GaussianNB_iris

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15yFq8Yp80BV_LCUGmW9p3ru20F-fAw3Y
"""

from sklearn.datasets import load_iris

iris = load_iris()
#iris

x = iris.data
y = iris.target
#x
#y

iris.DESCR

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=1)

#VISUALIZE THE DATASET
print(x.shape)
print(x_train.shape)
print(x_test.shape)

#CREATE THE CLASSIFIER
gnb = GaussianNB()
gnb #Takes variable smoothing = [1/sqrt(2*pi*sigma^2)] * -0.5 * ((x-mean)/sigma)^2)

#FIT THE MODEL ON TRAINING DATA
gnb.fit(x_train, y_train)

#PREDICT USING THE FIT MODEL
y_predicted = gnb.predict(x_test)
y_predicted

y_test

from sklearn import metrics

print(metrics.accuracy_score(y_test, y_predicted)*100)

