# -*- coding: utf-8 -*-
"""Iris_DTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19rhvqTPCYXgmCn-aJWjZsVKRFffiYe8f
"""

import pandas as pd
import sklearn

df = pd.read_csv("/content/iris.csv")

df

df.head()

from sklearn.tree import DecisionTreeClassifier
from sklearn import model_selection

array = df.values
X=array[:, 0:4]
Y=array[:, 4]
validation_size=0.30
seed=7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size = validation_size, random_state=seed)

dtc = DecisionTreeClassifier()
dtc.fit(X_train, Y_train)
predictions = dtc.predict(X_validation)

print(predictions)